# Generated by Django 5.2.13 on 2026-05-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailsummary_gmail_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsummary',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
