# Generated by Django 5.2.13 on 2026-05-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailsummary_gmail_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsummary',
            name='category',
            field=models.CharField(default='outro', max_length=50),
        ),
    ]
