# Generated by Django 5.2.13 on 2026-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailsummary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsummary',
            name='urgency_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
