# Generated by Django 5.2.13 on 2026-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailsummary_urgency_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPreferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('llama', 'Llama')], max_length=20)),
                ('action', models.CharField(choices=[('apply_label', 'Apply Label'), ('suggest_reply', 'Suggest Reply'), ('send_reply', 'Send Reply')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
