# Generated by Django 5.2.13 on 2026-06-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_llmpreferencelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmpreferencelog',
            name='action',
            field=models.CharField(choices=[('apply_label', 'Apply Label'), ('send_reply', 'Send Reply'), ('category_ok', 'Categoria correta'), ('category_not_ok', 'Categoria incorreta'), ('reply_good', 'Resposta boa'), ('reply_medium', 'Resposta média'), ('reply_bad', 'Resposta ruim')], max_length=30),
        ),
    ]
