# Generated by Django 5.2.13 on 2026-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_llmpreferencelog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmpreferencelog',
            name='action',
        ),
        migrations.AddField(
            model_name='llmpreferencelog',
            name='category_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmpreferencelog',
            name='label_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmpreferencelog',
            name='reply_quality',
            field=models.CharField(choices=[('nao_usou', 'Não usou'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='nao_usou', max_length=20),
        ),
        migrations.AddField(
            model_name='llmpreferencelog',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmpreferencelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='llmpreferencelog',
            constraint=models.UniqueConstraint(fields=('email_id', 'provider'), name='unique_llm_log_per_email_provider'),
        ),
    ]
